package com.elvan.neram.ui.mozhiyaakkam

/**
 * English (en) Language Dictionary.
 */
val en: Map<String, String> = mapOf(
    // ── Navigation ──
    K.navHome to "Home",
    K.navNeram to "Neram",
    K.navSchedule to "Schedule",
    K.navCalendar to "Calendar",
    K.navNotes to "Notes",

    // ── Common ──
    K.loading to "Loading...",
    K.error to "Error",
    K.retry to "Retry",
    K.save to "Save",
    K.delete to "Delete",
    K.confirm to "Confirm",
    K.back to "Back",
    K.cancel to "Cancel",
    K.ok to "OK",
    K.edit to "Edit",
    K.offline to "Offline",
    K.offlineMessage to "Internet is not connected. Connect to internet to sync data.",
    K.fromElvanNavil to "From Elvan Navil",
    K.elvanNavil to "Elvan Navil",
    K.elvanNavilDesc to "By Elvan Parthasarathy",
    K.elvanParthasarathy to "Elvan Parthasarathy",

    // ── Home Screen ──
    K.greeting to "Hello!",
    K.welcomeToNeram to "Welcome to Neram!",
    K.gladYouAreHere to "Glad you're here 😊",
    K.vanakkam to "Vanakkam!",
    K.selectDate to "Select date",
    K.academicCalendar to "Academic Calendar",
    K.schedule to "Schedule",
    K.workingDay to "Working Day",
    K.regularWorkingDay to "Regular Working Day",
    K.noEventsScheduled to "No events scheduled",
    K.followingOrder to "FOLLOWING %s ORDER",
    K.classesSuspended to "Classes Suspended",
    K.system to "System",
    K.noUpdates to "No special updates for today.",
    K.todaysEvent to "TODAY'S EVENT",
    K.specialEvent to "SPECIAL EVENT",
    K.fullDay to "Full Day",
    K.noClasses to "No Classes",
    K.event to "Event",
    K.todaysExam to "TODAY'S EXAM",
    K.todaysPracticalExam to "TODAY'S PRACTICAL EXAM",
    K.noClassesScheduled to "No classes scheduled.",
    K.liveUpdates to "Live Updates (%s)",
    K.generalNotice to "General Notice",
    K.noUpdatesForDate to "No updates for this date.",
    K.noGeneralNotices to "No general notices.",
    K.lab to "LAB",
    K.specialSession to "Special Session",
    K.fullDayEvent to "Full Day Event",
    K.postedBy to "Posted by ",
    K.typeHere to "Type here...",
    K.studentsCount to "%s Students",
    K.scheduledForToday to "Scheduled for Today",
    K.noEventsDeclared to "No events declared",
    K.systemReminder to "System Reminder",
    K.bringLabcoatsEssentials to "📚 Bring Labcoats, Laptops & Lab Essentials",
    K.studyWellExamWish to "📖 Study well for the test! Score well and get full marks! All the best! 🎯",
    K.noAcademicCalendarScheduled to "No Academic Calendar Scheduled",
    K.open to "Open",
    K.dismiss to "Dismiss",
    K.classesSuspendedDueTo to "Classes suspended due to %s.",
    K.userNotLoggedIn to "User not logged in.",
    K.failedToSaveUpdate to "Failed to save update",
    K.failedToSaveNotice to "Failed to save notice",
    K.failedToUpdatePlacement to "Failed to update placement",
    K.dept to "Dept",
    K.sec to "Sec",
    K.holiday to "Holiday",
    K.profile to "Profile",
    K.dayReservedFor to "Day reserved for %s.",
    K.regularClassesSuspendedDuring to "Regular classes are suspended during the %s period.",
    K.allDay to "All Day",
    K.explore to "Explore",
    K.monthView to "Month View",
    K.listView to "List View",
    K.menu to "Menu",
    K.cleanupFailed to "Cleanup failed",
    K.pushNotifications to "Notifications",
    K.notificationTimings to "Alerts, Timings & Preferences",
    K.notificationNote to "Note: Notification delivery depends on system battery optimization and network availability.",
    K.classCounselors to "Class Counselors",
    K.keyCoordinators to "Key Coordinators",
    K.noInfoAvailable to "No info available",
    K.noSubjectsScheduled to "No subjects scheduled for this day",
    K.noBatchesScheduled to "No batches scheduled",
    K.noCoursesFound to "No courses found",
    K.students to "%d Students",
    K.periods to "Periods",
    K.classesTab to "Classes",
    K.examsTab to "Exams",
    K.weeklySchedule to "Weekly Schedule",
    K.collapse to "Collapse",
    K.expand to "Expand",
    K.noClassesOn to "No classes on %s",
    K.ongoingExams to "Ongoing Exams",
    K.noOngoingExams to "No ongoing exams currently",
    K.noExamTimetables to "No exam timetables published yet",
    K.upcomingExams to "Upcoming Exams",
    K.finishedExams to "Completed Exams",
    K.academicCourses to "Academic Courses",
    K.cardUpdate to "Update",
    K.cardAlert to "Alert",
    K.cardNews to "News",
    K.cardTip to "Tip",
    K.cardNotice to "Notice",
    K.cardFeature to "Feature",
    K.officialDocuments to "Official Documents",
    K.downloadPdfForOffline to "Download PDF for offline use",
    K.linkCopiedToClipboard to "Link copied to clipboard",
    K.noAcademicEvents to "No academic events",
    K.noAcademicEventsFor to "No academic events for %s",
    K.noUpcomingEvents to "No upcoming events",
    K.rmdCollegeWebsiteDesc to "Official RMD college website.",
    K.rmkNextgenStudentDesc to "Nextgen platform for student login and academic tracking.",
    K.elvanNavilSiteDesc to "Campus news, articles, and student announcements platform.",
    K.iamNeoDesc to "Learning, assessment, and recruitment solutions.",
    K.skillRackDesc to "Daily coding challenges and problem-solving tasks.",
    K.codeTantraDesc to "Platform for classes, assignments, and assessments.",
    K.google to "Google",
    K.googleProfile to "Google Profile",
    K.googleAccountLinked to "Google account linked!",
    K.male to "Male",
    K.female to "Female",
    K.genderOther to "Other",
    K.morningWake to "Morning Wake",
    K.preCollege to "Pre-College",
    K.collegeEntry to "College Entry",
    K.selectTime to "Select Time",
    K.elvanNavilBranding to "Elvan Navil",
    K.allRightsReserved to "© All rights reserved",
    K.linkFailed to "Link failed",
    K.noIdTokenReceived to "No ID Token received",
    K.googleSignInFailed to "Google Sign-In Failed",
    K.couldNotLaunchGoogleSignIn to "Could not launch Google Sign-In",
    K.welcomeBack to "Welcome Back",
    K.signInToContinue to "Sign in to continue",
    K.emailAddress to "Email Address",
    K.createAccount to "Create Account",
    K.fillDetailsToGetStarted to "Fill in your details to get started",
    K.firstName to "First Name",
    K.lastName to "Last Name",
    K.signUpWithGoogle to "Sign up with Google",
    K.collegeTimeSorted to "Your College Time, Sorted.",
    K.tapAgreeAndContinue to "Tap \"Agree and Continue\" to get started with Neram.",
    K.agreeAndContinue to "Agree and Continue",
    K.profileSetup to "Profile Setup",
    K.selectAcademicDetailsBelow to "Select your academic details below",
    K.academicBatch to "Academic Batch",
    K.selectYear to "Select Year",
    K.completeSetup to "Complete Setup",
    K.previousMonth to "Previous Month",
    K.nextMonth to "Next Month",
    K.previousYear to "Previous Year",
    K.nextYear to "Next Year",
    K.noAcademicEventsScheduled to "No academic events scheduled.",
    K.goToToday to "Go to Today",
    K.eventsCount to "events",
    K.holidaysCount to "holidays",
    K.downloadingPdf to "Downloading PDF...",
    K.failedToLoadDocument to "Failed to load document",
    K.goBack to "Go Back",
    K.noItemsHere to "No items here",
    K.noUnitsAddedYet to "No units added yet",
    K.noNotifications to "No Notifications",
    K.markAllRead to "Mark all read",
    K.clearAll to "Clear all",
    K.identityVerifiedTryingAgain to "Identity verified! Trying again...",
    K.verifyCustomIdentity to "Verify Identity",
    K.verifyGoogleForPasswordDesc to "For security, please sign in with Google again to create a password.",
    K.verify to "Verify",
    K.googleAccountUnlinked to "Google account unlinked",
    K.identityVerifiedDeletingAccount to "Identity verified! Deleting account...",
    K.accountDeleted to "Account deleted",
    K.verifyIdentityForDeletion to "Verify Identity for Deletion",
    K.verifyGoogleForDeletionDesc to "Deleting your account is a sensitive action. Please sign in with Google again to confirm.",
    K.secretary to "Secretary",
    K.rsMunirathinamBio to "A dedicated visionary and philanthropist who served as a Former Member of the Tamil Nadu State Assembly and founded the R.M.K. Group of Institutions.",
    K.rmKishoreBio to "Mechanical Engineer with an MBA from UK, focused on transforming learners into achievers with global standards.",
    K.manjulaMunirathinamBio to "Keen social worker and educationalist with over a decade of dedication to the group.",
    K.jothiNaiduBio to "Vast experience in industrial management, associated with the group for nearly 30 years.",
    K.yalamanchiPradeepBio to "ECE Engineer (Guindy) with a Master's from Carnegie Mellon University, USA.",
    K.kavaraipettaiAddress to "Kavaraipettai, Thiruvallur District",
    K.puduvoyalAddress to "Puduvoyal, Thiruvallur District",
    K.thiruverkaduAddress to "Thiruverkadu, Chennai",
    K.sriDurgadeviPolytechnic to "Sri Durgadevi Polytechnic College",
    K.rmkMatricSchool to "R.M.K. Matriculation School",
    K.dontHaveAccount to "Don't have an account? ",
    K.alreadyHaveAccount to "Already have an account? ",
    K.signUp to "Sign Up",
    K.logIn to "Log In",
    K.orDivider to " OR ",
    K.continueWithGoogle to "Continue with Google",

    // ── Days of Week ──
    K.dayMonday to "Mon",
    K.dayTuesday to "Tue",
    K.dayWednesday to "Wed",
    K.dayThursday to "Thu",
    K.dayFriday to "Fri",
    K.daySaturday to "Sat",
    K.daySunday to "Sun",

    K.dayMondayFull to "Monday",
    K.dayTuesdayFull to "Tuesday",
    K.dayWednesdayFull to "Wednesday",
    K.dayThursdayFull to "Thursday",
    K.dayFridayFull to "Friday",
    K.daySaturdayFull to "Saturday",
    K.daySundayFull to "Sunday",

    K.dayMondayLong to "Monday",
    K.dayTuesdayLong to "Tuesday",
    K.dayWednesdayLong to "Wednesday",
    K.dayThursdayLong to "Thursday",
    K.dayFridayLong to "Friday",
    K.daySaturdayLong to "Saturday",
    K.daySundayLong to "Sunday",

    K.dayMondaySingle to "M",
    K.dayTuesdaySingle to "T",
    K.dayWednesdaySingle to "W",
    K.dayThursdaySingle to "T",
    K.dayFridaySingle to "F",
    K.daySaturdaySingle to "S",
    K.daySundaySingle to "S",

    // ── Months of Year ──
    K.monthJan to "January",
    K.monthFeb to "February",
    K.monthMar to "March",
    K.monthApr to "April",
    K.monthMay to "May",
    K.monthJun to "June",
    K.monthJul to "July",
    K.monthAug to "August",
    K.monthSep to "September",
    K.monthOct to "October",
    K.monthNov to "November",
    K.monthDec to "December",

    K.monthJanShort to "Jan",
    K.monthFebShort to "Feb",
    K.monthMarShort to "Mar",
    K.monthAprShort to "Apr",
    K.monthMayShort to "May",
    K.monthJunShort to "Jun",
    K.monthJulShort to "Jul",
    K.monthAugShort to "Aug",
    K.monthSepShort to "Sep",
    K.monthOctShort to "Oct",
    K.monthNovShort to "Nov",
    K.monthDecShort to "Dec",

    // ── Settings Hub ──
    K.settings to "Settings",
    K.neramAccount to "Neram Account",
    K.accounts to "Accounts",
    K.accountsDesc to "Linked accounts, Sign out",
    K.security to "Security",
    K.securityDesc to "Password, Delete account",
    K.userDirectory to "User Directory",
    K.userDirectoryDesc to "Faculty, Staff, Students",
    K.display to "Display",
    K.displayDesc to "Brightness, Dark mode",
    K.storageData to "Storage & Data",
    K.storageDesc to "Clear old updates, Manage cache",
    K.complaints to "Complaints & Feedback",
    K.complaintsDesc to "Report issues, Suggestions",
    K.aboutDeveloper to "About Designer",
    K.aboutDeveloperDesc to "Designer profile & contacts",
    K.aboutApp to "About App",
    K.aboutAppDesc to "Your College Time, Sorted",
    K.importantSites to "Important Sites",
    K.importantSitesDesc to "College portals, Quick links",
    K.aboutRmk to "About RMK Group",
    K.aboutRmkDesc to "Institutions, Leadership",
    K.contact to "Contact",
    K.contactDesc to "Campus helplines, Location",
    K.managementTeam to "Management Team",
    K.language to "Language",
    K.languageDesc to "English, Tamil, Tamil (Latin), Tamil (Malayalam Script), Malayalam, Malayalam (Latin), Malayalam (Tamil Script)",
    K.deviceLanguage to "System Default",
    K.english to "English",
    K.tamil to "Tamil",
    K.tamilLatin to "Tamil (Latin)",
    K.tamilMalayalam to "Tamil (Malayalam Script)",
    K.malayalam to "Malayalam",
    K.malayalamLatin to "Malayalam (Latin)",
    K.malayalamTamil to "Malayalam (Tamil Script)",
    K.telugu to "Telugu",
    K.teluguLatin to "Telugu (Latin)",
    K.languageInfo to "Language change applies immediately across all pages, navigation, and settings.",
    K.chooseLanguage to "Choose Language",
    K.selectPreferredLanguage to "Select your preferred language",
    K.moreLanguagesBelow to "Swipe for more languages",
    K.continueAction to "Continue",
    K.editProfile to "Profile",
    K.feedback to "Feedback & Queries",

    // ── Display Settings ──
    K.lightMode to "Light",
    K.darkMode to "Dark",
    K.systemAuto to "System Auto",
    K.themeDescription to "Switch modes with system",

    // ── Accounts & Security ──
    K.linkedAccounts to "Linked Accounts",
    K.linkedAccountsDesc to "Manage Google sign-in",
    K.signOut to "Sign Out",
    K.signOutDesc to "Log out of your Neram account",
    K.signOutConfirm to "Sign Out?",
    K.signOutMessage to "Are you sure you want to sign out?",
    K.changePassword to "Change Password",
    K.deleteAccount to "Delete Account",
    K.dangerZone to "DANGER ZONE",
    K.createPassword to "Create Password",

    // ── Storage Settings ──
    K.cleanupOptions to "CLEANUP OPTIONS",
    K.clearOldUpdates to "Clear Old Updates",
    K.clearOldUpdatesDesc to "Remove news & notices older than 30 days",
    K.customRangeDeletion to "Custom Range Deletion",
    K.customRangeDesc to "Select a date range to wipe updates",
    K.optimizationInfo to "Optimization helps keep the app responsive and saves local storage by removing old media and text records.",
    K.confirmDeletion to "Confirm Deletion",
    K.clearNow to "Clear Now",
    K.deleteData to "Delete Data",
    K.selectRange to "Select Range",
    K.selectDateRange to "Select Date Range",
    K.chooseUpdatesToWipe to "Choose updates to wipe",
    K.clearConfirmMessage to "This will delete all live updates and notices older than 30 days. This action cannot be undone.",
    K.clearedMessage to "Cleared updates older than 30 days",

    // ── Notes Screen ──
    K.notUploadedTitle to "Not Uploaded",
    K.notUploadedMessage to "The unit notes have not been uploaded in rmd.ac.in yet. They will appear here once available.",

    // ── User Directory ──
    K.noUsersFound to "No contacts found matching search.",
    K.email to "Email",

    // ── About App Screen ──
    K.whatIsNeram to "What is Neram?",
    K.aboutNeramDesc to "Neram (நேரம், meaning 'Time') is a sleek, intelligent campus companion and daily scheduler. It brings together everything you need to stay organized and informed throughout your academic day.\n\nFrom Elvan Navil\nCrafted with care to bring together your timetable, exams, notices, and notes in an intuitive, beautifully designed experience.",
    K.features to "FEATURES",
    K.smartTimetable to "Smart Timetable",
    K.smartTimetableDesc to "View your daily class schedule with faculty info, room numbers, and real-time updates.",
    K.examCalendar to "Exam Calendar",
    K.examCalendarDesc to "Track upcoming exams, internals, and important academic events with countdown timers.",
    K.campusAnnouncements to "Campus Announcements",
    K.campusAnnouncementsDesc to "Get instant notifications for news, circulars, and announcements from the college.",
    K.offlineSupport to "Offline Support",
    K.offlineSupportDesc to "Access your timetable and cached data even without an internet connection.",
    K.cloudSync to "Cloud Sync",
    K.cloudSyncDesc to "Your schedule and preferences sync seamlessly across devices with Firebase.",

    // ── Developer Info ──
    K.connectWithMe to "Connect With Me",
    K.visitPortfolio to "Visit Portfolio",
    K.locationChennai to "Arani / Chennai, Tamil Nadu",

    // ── Feedback & Complaints ──
    K.submitFeedback to "Submit Feedback",
    K.describeIssue to "Describe your feedback or issue in detail...",
    K.feedbackSubmittedSuccess to "Thank you! Your feedback has been submitted.",
    K.fillAllFields to "Please fill in all required fields",

    // ── RMK Group & Management ──
    K.rmkGroupLegacy to "RMK Group of Institutions",
    K.rmkDescription to "A premier group of educational institutions in Tamil Nadu dedicated to academic excellence, discipline, and modern engineering education.",
    K.visionMission to "Vision & Mission",
    K.institutions to "Institutions",
    K.rmkEnggCollege to "R.M.K. Engineering College",
    K.rmdEnggCollege to "R.M.D. Engineering College",
    K.rmkCet to "R.M.K. College of Engineering and Technology",
    K.rmkSchool to "R.M.K. Residential Senior Secondary School",
    K.founderChairman to "Founder & Chairman",
    K.viceChairman to "Vice Chairman",
    K.chairperson to "Chairperson",
    K.director to "Director",

    // ── College Sites ──
    K.officialPortals to "OFFICIAL PORTALS",

    // ── Contact & Emergency ──
    K.emergencyHelpline to "Emergency Helplines",
    K.collegeReception to "College Reception",
    K.principalOffice to "Principal's Office",
    K.placementCell to "Training & Placement Cell",
    K.transportIncharge to "Transport Incharge",
    K.hostelOffice to "Hostel Office",
    K.ambulanceMedical to "Ambulance & Medical Center",
    K.securityGate to "Main Security Gate",

    // ── Auth & Onboarding ──
    K.fullName to "Full Name",
    K.roleStudent to "Student",
    K.fillDetailsGetStarted to "Fill in your details to get started",
    K.welcomeToNeramTitle to "Welcome to Neram",
    K.yourCollegeTimeSorted to "Your College Time, Sorted.",

    // ── Profile Screen & Edit Dialogs ──
    K.personalInfo to "Personal Information",
    K.academicDetails to "Academic Details",
    K.editName to "Edit Name",
    K.enterFirstName to "Enter first name",
    K.enterLastName to "Enter last name",
    K.mobileNumber to "Mobile Number",
    K.editMobileNumber to "Edit Mobile Number",
    K.tenDigitNumber to "10-digit number",
    K.dateOfBirth to "Date of Birth",
    K.editDateOfBirth to "Edit Date of Birth",
    K.gender to "Gender",
    K.selectGender to "Select Gender",
    K.batchDeptSection to "Batch, Department & Section",
    K.editAcademicDetails to "Edit Academic Details",
    K.batch to "Batch",
    K.selectBatch to "Select Batch",
    K.department to "Department",
    K.selectDepartment to "Select Department",
    K.section to "Section",
    K.selectSection to "Select Section",
    K.registerNumber to "Register Number",
    K.editRegisterNumber to "Edit Register Number",
    K.enterRegisterNumber to "Enter register number",

    // ── Security & Account Settings ──
    K.updateLoginPassword to "Update your login password",
    K.createPasswordTitle to "Create Password",
    K.setPasswordEmailLogin to "Set a password for email login",
    K.permanentlyRemoveAccount to "Permanently remove your account",
    K.currentPassword to "Current Password",
    K.enterCurrentPassword to "Enter current password",
    K.newPassword to "New Password",
    K.enterNewPassword to "Enter new password",
    K.confirmNewPassword to "Confirm New Password",
    K.confirmPassword to "Confirm password",
    K.verifyIdentity to "Verify Identity",
    K.googleReauthPrompt to "For security, please sign in with Google again.",
    K.signInMethods to "Sign-in Methods",

    // ── Notification Settings ──
    K.allowNotifications to "Allow Notifications",
    K.masterNotificationSwitch to "Master switch for all app notifications",
    K.dailyUpdates to "Daily Updates",
    K.dailyUpdatesDesc to "Daily class notes & academic updates",
    K.generalNoticesTitle to "General Notices",
    K.generalNoticesDesc to "General announcements from college",
    K.classScheduleTitle to "Class Schedule",
    K.classScheduleDesc to "Today's timetable and subjects",
    K.labReminders to "Lab Reminders",
    K.labRemindersDesc to "Batch-specific labs and labcoat alerts",
    K.studyReminders to "Study Reminders",
    K.studyRemindersDesc to "Motivation for upcoming exams",
    K.examAlerts to "Exam Alerts",
    K.examAlertsDesc to "Reminders for Today / Tomorrow exams",
    K.eventReminders to "Event Reminders",
    K.eventRemindersDesc to "Holidays and special events",
    K.instantAlerts to "Instant Alerts",
    K.instantAlertsDesc to "Critical instant announcements",
    K.useCustomTimes to "Use Custom Times",
    K.usingCustomTimes to "Using custom alarm times",
    K.usingDefaultTimes to "Using default college timings",
    K.dailyBriefing to "Daily Briefing",
    K.examToday to "Exam Today",
    K.examTomorrow to "Exam Tomorrow",
    K.practicalExamToday to "Practical Exam Today",
    K.practicalExamTomorrow to "Practical Exam Tomorrow",
    K.specialClassToday to "Special Class Today",
    K.bestOfLuckFor to "Best of luck for",
    K.prepareFor to "Prepare for",
    K.holidayToday to "Holiday Today",
    K.fullDayNotice to "Full Day Notice",
    K.halfDayNotice to "Half Day Notice",
    K.sectionNotice to "Section Notice",
    K.academicCalendarUpdate to "Academic Calendar Update",
    K.automatedReminders to "Automated Reminders",
    K.todaysSchedule to "Today's Schedule",
    K.time to "Time",
    K.user to "User",
    K.noEmailLinked to "No email linked",
    K.cannotOpenUrl to "Cannot open: %s",

    // ── User Directory Navigation ──
    K.selectBatchTitle to "Select Batch",
    K.viewDeptsInBatch to "View departments in batch %s",
    K.selectDeptBatch to "Select Department (Batch %s)",
    K.viewSectionsInDept to "View sections in %s",
    K.selectSectionDept to "Select Section (%s)",
    K.viewStudentsInSection to "View students in section %s",

    // ── Calendar Views ──
    K.viewMonth to "Month",
    K.viewSchedule to "Schedule",
    K.viewYear to "Year",

    // ── About & Management & Developer ──
    K.globalExcellence to "Global Excellence",
    K.globalExcellenceDesc to "To be the most preferred destination in the country for pursuing education in Engineering and its allied fields.",
    K.transformingLearners to "Transforming Learners",
    K.transformingLearnersDesc to "To transform learners into achievers at the global level with the right attitude towards changing societal needs.",
    K.location to "Location",
    K.managementTeamDesc to "The visionaries driving excellence and innovation across the RMK Group.",
    K.founders to "FOUNDERS",
    K.boardOfDirectors to "BOARD OF DIRECTORS",

    // ── Profile Screen Actions ──
    K.yourName to "Your Name",
    K.photoSyncedSuccess to "Photo synced successfully",
    K.syncFailed to "Sync failed: ",
    K.noGoogleAccountLinked to "No Google account linked",
    K.noPhotoInGoogleAccount to "No photo found in Google account",
    K.syncGooglePhoto to "Sync Google Photo",

    // ── Security & Authentication Dialogs ──
    K.forgotPassword to "Forgot Password?",
    K.confirmIdentityBeforeNewPassword to "Confirm your identity before setting a new password.",
    K.incorrectPassword to "Incorrect password",
    K.verifyAndContinue to "Verify & Continue",
    K.resetEmailSent to "Reset email sent to %s",
    K.createNewPassword to "Create your new password",
    K.updatePassword to "Update Password",
    K.atLeast6Chars to "At least 6 characters",
    K.passwordsMatch to "Passwords match",
    K.passwordUpdated to "Password Updated!",
    K.returningToSecuritySettings to "Returning to security settings...",
    K.signedInWithGoogleCreatePassword to "You signed in with Google. Create a password to also sign in with email.",
    K.passwordCreated to "Password Created!",
    K.canNowSignInWithEmail to "You can now sign in with email too.",
    K.unlink to "Unlink",
    K.unlinkGoogleAccount to "Unlink Google Account?",
    K.unlinkGoogleDesc to "You will need to sign in with your email and password after unlinking.",
    K.mustCreatePasswordFirst to "You must create a password first before unlinking Google, otherwise you won't be able to sign in.",
    K.password to "Password",
    K.passwordSet to "Password set",
    K.noPasswordSet to "No password set",
    K.thisActionIsPermanent to "This action is permanent",
    K.deleteAccountWarning to "Deleting your account removes your schedule, notes, and academic preferences. This cannot be undone.",
    K.iUnderstandContinue to "I understand, continue",
    K.confirmDeletionDesc to "Type DELETE in the box below to permanently delete your account.",
    K.typeDeleteToConfirm to "Type DELETE to confirm",
    K.returningToAuth to "Returning to login screen...",
    K.deleteAccountPermanently to "Delete Account Permanently",
    K.unlinkGoogleDescNoPassword to "You must create a password for your email before unlinking Google.",
    K.unlinkGoogleDescHasPassword to "Are you sure you want to unlink your Google account? You will still be able to sign in with your email and password.",
    K.verificationFailed to "Verification failed",
    K.refresh to "Refresh",
    K.isRequired to "is required",
    K.documents to "Documents",
    K.emailPassword to "EMAIL & PASSWORD",
    K.connected to "Connected",
    K.notConnected to "Not connected",
    K.create to "Create",
    K.linkedAccountsInfoText to "Linking your Google account allows faster and secure one-tap sign-in to Neram.",
    K.linkGoogle to "Link Google Account",
    K.unlinkGoogle to "Unlink Google Account",
    K.unlinkConfirm to "Unlink Google Account?",
    K.unlinkMessage to "Are you sure you want to unlink your Google account?",
    K.createPasswordMsg to "Before unlinking Google, you need to create a password so you can still log in.",
    K.createPasswordFirst to "Please create a password first",
    K.noAccountFound to "No account found with this email",
    K.invalidEmailFormat to "Invalid email format",
    K.authFailed to "Authentication failed",
    K.firstNameTooShort to "First Name must be at least 2 characters",
    K.invalidRegisterNumber to "Invalid Register Number",
    K.passwordTooShort to "Password must be at least 6 characters",
    K.signupFailedNoUser to "Signup failed - no user created",
    K.signupFailed to "Signup Failed",
    K.failedToUnlink to "Failed to unlink",
    K.showPassword to "Show password",
    K.hidePassword to "Hide password",
    K.home to "Home",
    K.calendar to "Calendar",
    K.notes to "Notes",
    K.notesDriveTab to "Notes Drive",
    K.collegeSiteTab to "College Site",
    K.notAvailable to "Not Available",
    K.readMore to "Read more",
    K.today to "Today",
    K.done to "Done",

    // ── Prebuilt Notifications & UI Texts ──
    K.linkedin to "LinkedIn",
    K.github to "GitHub",
    K.labForBatch to "Lab for Batch %s: %s",
    K.authorAttribution to " - %s",
    K.batchLabelFormat to "Batch %s",
    K.registerRangeFormat to "Reg: %s",
    K.studentsCountFormat to "%s Students",
    K.newExamSchedule to "New Exam Schedule: %s",
    K.newExam to "New Exam: %s",
    K.examDatesRange to "Dates: %s - %s",
    K.newHolidayAdded to "New Holiday Added",
    K.newEvent to "New Event: %s",
    K.eventOnDate to "%s on %s",
    K.newNotice to "New Notice",
    K.dailyUpdateFormat to "Daily Update (%s)",
    K.newClassEvent to "New Class Event: %s",
    K.clipboardPdfLinkLabel to "PDF Link",
    K.rmkTitle to "RMK",
    K.groupOfInstitutions to "Group of Institutions",
    K.roleAdmin to "Admin",
    K.admin to "Admin",
    K.accessDeniedRoleMustUseAdmin to "Access Denied: %s role must use the Admin Portal.",
    K.failedToLoadNotes to "Failed to load notes",
    K.unknownError to "Unknown error",
    K.notesDrive to "Notes Drive",
)
