package com.elvan.neram.ui.mozhiyaakkam

/**
 * Master Key Constants for Neram UI Translations.
 * Modeled after Elvan Niril's K translation catalog.
 */
object K {
    // Language Codes
    const val SYSTEM = "system"
    const val ENGLISH = "en"
    const val TAMIL = "ta"
    const val TAMIL_LATIN = "ta-Latn"

    /**
     * Get the effective language code based on user preference.
     */
    fun getEffectiveLanguage(preference: String, context: android.content.Context? = null): String {
        return when (preference) {
            ENGLISH -> ENGLISH
            TAMIL -> TAMIL
            TAMIL_LATIN -> TAMIL_LATIN
            SYSTEM -> {
                val deviceLocale = android.content.res.Resources.getSystem().configuration.locales[0]
                if (deviceLocale.language == "ta") TAMIL else ENGLISH
            }
            else -> ENGLISH
        }
    }

    // ── Navigation ──
    const val navHome = "navHome"
    const val navNeram = "navNeram"
    const val navSchedule = "navSchedule"
    const val navCalendar = "navCalendar"
    const val navNotes = "navNotes"

    // ── Common ──
    const val loading = "loading"
    const val error = "error"
    const val retry = "retry"
    const val save = "save"
    const val delete = "delete"
    const val confirm = "confirm"
    const val back = "back"
    const val cancel = "cancel"
    const val ok = "ok"
    const val edit = "edit"
    const val offline = "offline"
    const val offlineMessage = "offlineMessage"
    const val fromElvanNavil = "fromElvanNavil"
    const val elvanNavil = "elvanNavil"
    const val elvanNavilDesc = "elvanNavilDesc"
    const val elvanParthasarathy = "elvanParthasarathy"

    // ── Home Screen ──
    const val greeting = "greeting"
    const val welcomeToNeram = "welcomeToNeram"
    const val gladYouAreHere = "gladYouAreHere"
    const val vanakkam = "vanakkam"
    const val selectDate = "selectDate"
    const val academicCalendar = "academicCalendar"
    const val schedule = "schedule"
    const val workingDay = "workingDay"
    const val regularWorkingDay = "regularWorkingDay"
    const val noEventsScheduled = "noEventsScheduled"
    const val followingOrder = "followingOrder"
    const val classesSuspended = "classesSuspended"
    const val system = "system"
    const val noUpdates = "noUpdates"
    const val todaysEvent = "todaysEvent"
    const val specialEvent = "specialEvent"
    const val fullDay = "fullDay"
    const val noClasses = "noClasses"
    const val event = "event"
    const val todaysExam = "todaysExam"
    const val todaysPracticalExam = "todaysPracticalExam"
    const val noClassesScheduled = "noClassesScheduled"
    const val liveUpdates = "liveUpdates"
    const val generalNotice = "generalNotice"
    const val noUpdatesForDate = "noUpdatesForDate"
    const val noGeneralNotices = "noGeneralNotices"
    const val lab = "lab"
    const val specialSession = "specialSession"
    const val fullDayEvent = "fullDayEvent"
    const val postedBy = "postedBy"
    const val typeHere = "typeHere"
    const val studentsCount = "studentsCount"
    const val scheduledForToday = "scheduledForToday"
    const val noEventsDeclared = "noEventsDeclared"
    const val systemReminder = "systemReminder"
    const val bringLabcoatsEssentials = "bringLabcoatsEssentials"
    const val studyWellExamWish = "studyWellExamWish"
    const val noAcademicCalendarScheduled = "noAcademicCalendarScheduled"
    const val open = "open"
    const val dismiss = "dismiss"
    const val classesSuspendedDueTo = "classesSuspendedDueTo"
    const val userNotLoggedIn = "userNotLoggedIn"
    const val failedToSaveUpdate = "failedToSaveUpdate"
    const val failedToSaveNotice = "failedToSaveNotice"
    const val failedToUpdatePlacement = "failedToUpdatePlacement"
    const val dept = "dept"
    const val sec = "sec"
    const val holiday = "holiday"
    const val profile = "profile"
    const val dayReservedFor = "dayReservedFor"
    const val regularClassesSuspendedDuring = "regularClassesSuspendedDuring"
    const val allDay = "allDay"
    const val explore = "explore"
    const val monthView = "monthView"
    const val listView = "listView"
    const val menu = "menu"
    const val cleanupFailed = "cleanupFailed"
    const val pushNotifications = "pushNotifications"
    const val notificationTimings = "notificationTimings"
    const val notificationNote = "notificationNote"
    const val classCounselors = "classCounselors"
    const val keyCoordinators = "keyCoordinators"
    const val noInfoAvailable = "noInfoAvailable"
    const val noSubjectsScheduled = "noSubjectsScheduled"
    const val noBatchesScheduled = "noBatchesScheduled"
    const val noCoursesFound = "noCoursesFound"
    const val students = "students"
    const val periods = "periods"
    const val classesTab = "classesTab"
    const val examsTab = "examsTab"
    const val weeklySchedule = "weeklySchedule"
    const val collapse = "collapse"
    const val expand = "expand"
    const val noClassesOn = "noClassesOn"
    const val ongoingExams = "ongoingExams"
    const val noOngoingExams = "noOngoingExams"
    const val noExamTimetables = "noExamTimetables"
    const val upcomingExams = "upcomingExams"
    const val finishedExams = "finishedExams"
    const val academicCourses = "academicCourses"
    const val cardUpdate = "cardUpdate"
    const val cardAlert = "cardAlert"
    const val cardNews = "cardNews"
    const val cardTip = "cardTip"
    const val cardNotice = "cardNotice"
    const val cardFeature = "cardFeature"
    const val officialDocuments = "officialDocuments"
    const val downloadPdfForOffline = "downloadPdfForOffline"
    const val linkCopiedToClipboard = "linkCopiedToClipboard"
    const val noAcademicEvents = "noAcademicEvents"
    const val noAcademicEventsFor = "noAcademicEventsFor"
    const val noUpcomingEvents = "noUpcomingEvents"
    const val rmdCollegeWebsiteDesc = "rmdCollegeWebsiteDesc"
    const val rmkNextgenStudentDesc = "rmkNextgenStudentDesc"
    const val elvanNavilSiteDesc = "elvanNavilSiteDesc"
    const val iamNeoDesc = "iamNeoDesc"
    const val skillRackDesc = "skillRackDesc"
    const val codeTantraDesc = "codeTantraDesc"
    const val google = "google"
    const val googleProfile = "googleProfile"
    const val googleAccountLinked = "googleAccountLinked"
    const val male = "male"
    const val female = "female"
    const val genderOther = "genderOther"
    const val morningWake = "morningWake"
    const val preCollege = "preCollege"
    const val collegeEntry = "collegeEntry"
    const val selectTime = "selectTime"
    const val elvanNavilBranding = "elvanNavilBranding"
    const val allRightsReserved = "allRightsReserved"
    const val linkFailed = "linkFailed"
    const val noIdTokenReceived = "noIdTokenReceived"
    const val googleSignInFailed = "googleSignInFailed"
    const val couldNotLaunchGoogleSignIn = "couldNotLaunchGoogleSignIn"
    const val welcomeBack = "welcomeBack"
    const val signInToContinue = "signInToContinue"
    const val emailAddress = "emailAddress"
    const val createAccount = "createAccount"
    const val fillDetailsToGetStarted = "fillDetailsToGetStarted"
    const val firstName = "firstName"
    const val lastName = "lastName"
    const val signUpWithGoogle = "signUpWithGoogle"
    const val collegeTimeSorted = "collegeTimeSorted"
    const val tapAgreeAndContinue = "tapAgreeAndContinue"
    const val agreeAndContinue = "agreeAndContinue"
    const val profileSetup = "profileSetup"
    const val selectAcademicDetailsBelow = "selectAcademicDetailsBelow"
    const val academicBatch = "academicBatch"
    const val selectYear = "selectYear"
    const val completeSetup = "completeSetup"
    const val previousMonth = "previousMonth"
    const val nextMonth = "nextMonth"
    const val previousYear = "previousYear"
    const val nextYear = "nextYear"
    const val noAcademicEventsScheduled = "noAcademicEventsScheduled"
    const val goToToday = "goToToday"
    const val eventsCount = "eventsCount"
    const val holidaysCount = "holidaysCount"
    const val downloadingPdf = "downloadingPdf"
    const val failedToLoadDocument = "failedToLoadDocument"
    const val goBack = "goBack"
    const val noItemsHere = "noItemsHere"
    const val noUnitsAddedYet = "noUnitsAddedYet"
    const val noNotifications = "noNotifications"
    const val markAllRead = "markAllRead"
    const val clearAll = "clearAll"
    const val identityVerifiedTryingAgain = "identityVerifiedTryingAgain"
    const val verifyCustomIdentity = "verifyCustomIdentity"
    const val verifyGoogleForPasswordDesc = "verifyGoogleForPasswordDesc"
    const val verify = "verify"
    const val googleAccountUnlinked = "googleAccountUnlinked"
    const val identityVerifiedDeletingAccount = "identityVerifiedDeletingAccount"
    const val accountDeleted = "accountDeleted"
    const val verifyIdentityForDeletion = "verifyIdentityForDeletion"
    const val verifyGoogleForDeletionDesc = "verifyGoogleForDeletionDesc"
    const val secretary = "secretary"
    const val rsMunirathinamBio = "rsMunirathinamBio"
    const val rmKishoreBio = "rmKishoreBio"
    const val manjulaMunirathinamBio = "manjulaMunirathinamBio"
    const val jothiNaiduBio = "jothiNaiduBio"
    const val yalamanchiPradeepBio = "yalamanchiPradeepBio"
    const val kavaraipettaiAddress = "kavaraipettaiAddress"
    const val puduvoyalAddress = "puduvoyalAddress"
    const val thiruverkaduAddress = "thiruverkaduAddress"
    const val sriDurgadeviPolytechnic = "sriDurgadeviPolytechnic"
    const val rmkMatricSchool = "rmkMatricSchool"
    const val dontHaveAccount = "dontHaveAccount"
    const val alreadyHaveAccount = "alreadyHaveAccount"
    const val signUp = "signUp"
    const val logIn = "logIn"
    const val orDivider = "orDivider"
    const val continueWithGoogle = "continueWithGoogle"

    // ── Days of Week ──
    const val dayMonday = "dayMonday"
    const val dayTuesday = "dayTuesday"
    const val dayWednesday = "dayWednesday"
    const val dayThursday = "dayThursday"
    const val dayFriday = "dayFriday"
    const val daySaturday = "daySaturday"
    const val daySunday = "daySunday"

    const val dayMondayFull = "dayMondayFull"
    const val dayTuesdayFull = "dayTuesdayFull"
    const val dayWednesdayFull = "dayWednesdayFull"
    const val dayThursdayFull = "dayThursdayFull"
    const val dayFridayFull = "dayFridayFull"
    const val daySaturdayFull = "daySaturdayFull"
    const val daySundayFull = "daySundayFull"

    const val dayMondayLong = "dayMondayLong"
    const val dayTuesdayLong = "dayTuesdayLong"
    const val dayWednesdayLong = "dayWednesdayLong"
    const val dayThursdayLong = "dayThursdayLong"
    const val dayFridayLong = "dayFridayLong"
    const val daySaturdayLong = "daySaturdayLong"
    const val daySundayLong = "daySundayLong"

    const val dayMondaySingle = "dayMondaySingle"
    const val dayTuesdaySingle = "dayTuesdaySingle"
    const val dayWednesdaySingle = "dayWednesdaySingle"
    const val dayThursdaySingle = "dayThursdaySingle"
    const val dayFridaySingle = "dayFridaySingle"
    const val daySaturdaySingle = "daySaturdaySingle"
    const val daySundaySingle = "daySundaySingle"

    // ── Months of Year ──
    const val monthJan = "monthJan"
    const val monthFeb = "monthFeb"
    const val monthMar = "monthMar"
    const val monthApr = "monthApr"
    const val monthMay = "monthMay"
    const val monthJun = "monthJun"
    const val monthJul = "monthJul"
    const val monthAug = "monthAug"
    const val monthSep = "monthSep"
    const val monthOct = "monthOct"
    const val monthNov = "monthNov"
    const val monthDec = "monthDec"

    const val monthJanShort = "monthJanShort"
    const val monthFebShort = "monthFebShort"
    const val monthMarShort = "monthMarShort"
    const val monthAprShort = "monthAprShort"
    const val monthMayShort = "monthMayShort"
    const val monthJunShort = "monthJunShort"
    const val monthJulShort = "monthJulShort"
    const val monthAugShort = "monthAugShort"
    const val monthSepShort = "monthSepShort"
    const val monthOctShort = "monthOctShort"
    const val monthNovShort = "monthNovShort"
    const val monthDecShort = "monthDecShort"

    // ── Settings Hub ──
    const val settings = "settings"
    const val neramAccount = "neramAccount"
    const val accounts = "accounts"
    const val accountsDesc = "accountsDesc"
    const val security = "security"
    const val securityDesc = "securityDesc"
    const val userDirectory = "userDirectory"
    const val userDirectoryDesc = "userDirectoryDesc"
    const val display = "display"
    const val displayDesc = "displayDesc"
    const val storageData = "storageData"
    const val storageDesc = "storageDesc"
    const val complaints = "complaints"
    const val complaintsDesc = "complaintsDesc"
    const val aboutDeveloper = "aboutDeveloper"
    const val aboutDeveloperDesc = "aboutDeveloperDesc"
    const val aboutApp = "aboutApp"
    const val aboutAppDesc = "aboutAppDesc"
    const val importantSites = "importantSites"
    const val importantSitesDesc = "importantSitesDesc"
    const val aboutRmk = "aboutRmk"
    const val aboutRmkDesc = "aboutRmkDesc"
    const val contact = "contact"
    const val contactDesc = "contactDesc"
    const val managementTeam = "managementTeam"
    const val language = "language"
    const val languageDesc = "languageDesc"
    const val deviceLanguage = "deviceLanguage"
    const val english = "english"
    const val tamil = "tamil"
    const val tamilLatin = "tamilLatin"
    const val languageInfo = "languageInfo"
    const val editProfile = "editProfile"
    const val feedback = "feedback"

    // ── Display Settings ──
    const val lightMode = "lightMode"
    const val darkMode = "darkMode"
    const val systemAuto = "systemAuto"
    const val themeDescription = "themeDescription"

    // ── Accounts & Security ──
    const val linkedAccounts = "linkedAccounts"
    const val linkedAccountsDesc = "linkedAccountsDesc"
    const val signOut = "signOut"
    const val signOutDesc = "signOutDesc"
    const val signOutConfirm = "signOutConfirm"
    const val signOutMessage = "signOutMessage"
    const val changePassword = "changePassword"
    const val deleteAccount = "deleteAccount"
    const val dangerZone = "dangerZone"
    const val createPassword = "createPassword"

    // ── Storage Settings ──
    const val cleanupOptions = "cleanupOptions"
    const val clearOldUpdates = "clearOldUpdates"
    const val clearOldUpdatesDesc = "clearOldUpdatesDesc"
    const val customRangeDeletion = "customRangeDeletion"
    const val customRangeDesc = "customRangeDesc"
    const val optimizationInfo = "optimizationInfo"
    const val confirmDeletion = "confirmDeletion"
    const val clearNow = "clearNow"
    const val deleteData = "deleteData"
    const val selectRange = "selectRange"
    const val selectDateRange = "selectDateRange"
    const val chooseUpdatesToWipe = "chooseUpdatesToWipe"
    const val clearConfirmMessage = "clearConfirmMessage"
    const val clearedMessage = "clearedMessage"

    // ── Notes Screen ──
    const val notUploadedTitle = "notUploadedTitle"
    const val notUploadedMessage = "notUploadedMessage"
    const val unit = "unit"

    // ── User Directory ──
    const val noUsersFound = "noUsersFound"
    const val email = "email"

    // ── About App Screen ──
    const val whatIsNeram = "whatIsNeram"
    const val aboutNeramDesc = "aboutNeramDesc"
    const val features = "features"
    const val smartTimetable = "smartTimetable"
    const val smartTimetableDesc = "smartTimetableDesc"
    const val examCalendar = "examCalendar"
    const val examCalendarDesc = "examCalendarDesc"
    const val campusAnnouncements = "campusAnnouncements"
    const val campusAnnouncementsDesc = "campusAnnouncementsDesc"
    const val offlineSupport = "offlineSupport"
    const val offlineSupportDesc = "offlineSupportDesc"
    const val cloudSync = "cloudSync"
    const val cloudSyncDesc = "cloudSyncDesc"

    // ── Developer Info ──
    const val connectWithMe = "connectWithMe"
    const val visitPortfolio = "visitPortfolio"
    const val locationChennai = "locationChennai"

    // ── Feedback & Complaints ──
    const val submitFeedback = "submitFeedback"
    const val describeIssue = "describeIssue"
    const val feedbackSubmittedSuccess = "feedbackSubmittedSuccess"
    const val fillAllFields = "fillAllFields"

    // ── RMK Group & Management ──
    const val rmkGroupLegacy = "rmkGroupLegacy"
    const val rmkDescription = "rmkDescription"
    const val visionMission = "visionMission"
    const val institutions = "institutions"
    const val rmkEnggCollege = "rmkEnggCollege"
    const val rmdEnggCollege = "rmdEnggCollege"
    const val rmkCet = "rmkCet"
    const val rmkSchool = "rmkSchool"
    const val founderChairman = "founderChairman"
    const val viceChairman = "viceChairman"
    const val chairperson = "chairperson"
    const val director = "director"

    // ── College Sites ──
    const val officialPortals = "officialPortals"

    // ── Contact & Emergency ──
    const val emergencyHelpline = "emergencyHelpline"
    const val collegeReception = "collegeReception"
    const val principalOffice = "principalOffice"
    const val placementCell = "placementCell"
    const val transportIncharge = "transportIncharge"
    const val hostelOffice = "hostelOffice"
    const val ambulanceMedical = "ambulanceMedical"
    const val securityGate = "securityGate"

    // ── Auth & Onboarding ──
    const val fullName = "fullName"
    const val roleStudent = "roleStudent"
    const val fillDetailsGetStarted = "fillDetailsGetStarted"
    const val welcomeToNeramTitle = "welcomeToNeramTitle"
    const val yourCollegeTimeSorted = "yourCollegeTimeSorted"

    // ── Profile Screen & Edit Dialogs ──
    const val personalInfo = "personalInfo"
    const val academicDetails = "academicDetails"
    const val editName = "editName"
    const val enterFirstName = "enterFirstName"
    const val enterLastName = "enterLastName"
    const val mobileNumber = "mobileNumber"
    const val editMobileNumber = "editMobileNumber"
    const val tenDigitNumber = "tenDigitNumber"
    const val dateOfBirth = "dateOfBirth"
    const val editDateOfBirth = "editDateOfBirth"
    const val gender = "gender"
    const val selectGender = "selectGender"
    const val batchDeptSection = "batchDeptSection"
    const val editAcademicDetails = "editAcademicDetails"
    const val batch = "batch"
    const val selectBatch = "selectBatch"
    const val department = "department"
    const val selectDepartment = "selectDepartment"
    const val section = "section"
    const val selectSection = "selectSection"
    const val registerNumber = "registerNumber"
    const val editRegisterNumber = "editRegisterNumber"
    const val enterRegisterNumber = "enterRegisterNumber"

    // ── Security & Account Settings ──
    const val updateLoginPassword = "updateLoginPassword"
    const val createPasswordTitle = "createPasswordTitle"
    const val setPasswordEmailLogin = "setPasswordEmailLogin"
    const val permanentlyRemoveAccount = "permanentlyRemoveAccount"
    const val currentPassword = "currentPassword"
    const val enterCurrentPassword = "enterCurrentPassword"
    const val newPassword = "newPassword"
    const val enterNewPassword = "enterNewPassword"
    const val confirmNewPassword = "confirmNewPassword"
    const val confirmPassword = "confirmPassword"
    const val verifyIdentity = "verifyIdentity"
    const val googleReauthPrompt = "googleReauthPrompt"
    const val signInMethods = "signInMethods"

    // ── Notification Settings ──
    const val allowNotifications = "allowNotifications"
    const val masterNotificationSwitch = "masterNotificationSwitch"
    const val dailyUpdates = "dailyUpdates"
    const val dailyUpdatesDesc = "dailyUpdatesDesc"
    const val generalNoticesTitle = "generalNoticesTitle"
    const val generalNoticesDesc = "generalNoticesDesc"
    const val classScheduleTitle = "classScheduleTitle"
    const val classScheduleDesc = "classScheduleDesc"
    const val labReminders = "labReminders"
    const val labRemindersDesc = "labRemindersDesc"
    const val studyReminders = "studyReminders"
    const val studyRemindersDesc = "studyRemindersDesc"
    const val examAlerts = "examAlerts"
    const val examAlertsDesc = "examAlertsDesc"
    const val eventReminders = "eventReminders"
    const val eventRemindersDesc = "eventRemindersDesc"
    const val instantAlerts = "instantAlerts"
    const val instantAlertsDesc = "instantAlertsDesc"
    const val useCustomTimes = "useCustomTimes"
    const val usingCustomTimes = "usingCustomTimes"
    const val usingDefaultTimes = "usingDefaultTimes"
    const val dailyBriefing = "dailyBriefing"
    const val examToday = "examToday"
    const val examTomorrow = "examTomorrow"
    const val practicalExamToday = "practicalExamToday"
    const val practicalExamTomorrow = "practicalExamTomorrow"
    const val specialClassToday = "specialClassToday"
    const val bestOfLuckFor = "bestOfLuckFor"
    const val prepareFor = "prepareFor"
    const val holidayToday = "holidayToday"
    const val fullDayNotice = "fullDayNotice"
    const val halfDayNotice = "halfDayNotice"
    const val sectionNotice = "sectionNotice"
    const val academicCalendarUpdate = "academicCalendarUpdate"
    const val automatedReminders = "automatedReminders"
    const val todaysSchedule = "todaysSchedule"
    const val time = "time"
    const val user = "user"
    const val noEmailLinked = "noEmailLinked"
    const val cannotOpenUrl = "cannotOpenUrl"

    // ── User Directory Navigation ──
    const val selectBatchTitle = "selectBatchTitle"
    const val viewDeptsInBatch = "viewDeptsInBatch"
    const val selectDeptBatch = "selectDeptBatch"
    const val viewSectionsInDept = "viewSectionsInDept"
    const val selectSectionDept = "selectSectionDept"
    const val viewStudentsInSection = "viewStudentsInSection"

    // ── Calendar Views ──
    const val viewMonth = "viewMonth"
    const val viewSchedule = "viewSchedule"
    const val viewYear = "viewYear"

    // ── About & Management & Developer ──
    const val globalExcellence = "globalExcellence"
    const val globalExcellenceDesc = "globalExcellenceDesc"
    const val transformingLearners = "transformingLearners"
    const val transformingLearnersDesc = "transformingLearnersDesc"
    const val location = "location"
    const val managementTeamDesc = "managementTeamDesc"
    const val founders = "founders"
    const val boardOfDirectors = "boardOfDirectors"

    // ── Profile Screen Actions ──
    const val yourName = "yourName"
    const val photoSyncedSuccess = "photoSyncedSuccess"
    const val syncFailed = "syncFailed"
    const val noGoogleAccountLinked = "noGoogleAccountLinked"
    const val noPhotoInGoogleAccount = "noPhotoInGoogleAccount"
    const val syncGooglePhoto = "syncGooglePhoto"

    // ── Security & Authentication Dialogs ──
    const val forgotPassword = "forgotPassword"
    const val confirmIdentityBeforeNewPassword = "confirmIdentityBeforeNewPassword"
    const val incorrectPassword = "incorrectPassword"
    const val verifyAndContinue = "verifyAndContinue"
    const val resetEmailSent = "resetEmailSent"
    const val createNewPassword = "createNewPassword"
    const val updatePassword = "updatePassword"
    const val atLeast6Chars = "atLeast6Chars"
    const val passwordsMatch = "passwordsMatch"
    const val passwordUpdated = "passwordUpdated"
    const val returningToSecuritySettings = "returningToSecuritySettings"
    const val signedInWithGoogleCreatePassword = "signedInWithGoogleCreatePassword"
    const val passwordCreated = "passwordCreated"
    const val canNowSignInWithEmail = "canNowSignInWithEmail"
    const val unlink = "unlink"
    const val unlinkGoogleAccount = "unlinkGoogleAccount"
    const val unlinkGoogleDesc = "unlinkGoogleDesc"
    const val mustCreatePasswordFirst = "mustCreatePasswordFirst"
    const val password = "password"
    const val passwordSet = "passwordSet"
    const val noPasswordSet = "noPasswordSet"
    const val thisActionIsPermanent = "thisActionIsPermanent"
    const val deleteAccountWarning = "deleteAccountWarning"
    const val iUnderstandContinue = "iUnderstandContinue"
    const val confirmDeletionDesc = "confirmDeletionDesc"
    const val typeDeleteToConfirm = "typeDeleteToConfirm"
    const val returningToAuth = "returningToAuth"
    const val deleteAccountPermanently = "deleteAccountPermanently"
    const val unlinkGoogleDescNoPassword = "unlinkGoogleDescNoPassword"
    const val unlinkGoogleDescHasPassword = "unlinkGoogleDescHasPassword"
    const val verificationFailed = "verificationFailed"
    const val refresh = "refresh"
    const val isRequired = "isRequired"
    const val documents = "documents"
    const val emailPassword = "emailPassword"
    const val connected = "connected"
    const val notConnected = "notConnected"
    const val create = "create"
    const val linkedAccountsInfoText = "linkedAccountsInfoText"
    const val linkGoogle = "linkGoogle"
    const val unlinkGoogle = "unlinkGoogle"
    const val unlinkConfirm = "unlinkConfirm"
    const val unlinkMessage = "unlinkMessage"
    const val createPasswordMsg = "createPasswordMsg"
    const val createPasswordFirst = "createPasswordFirst"
    const val noAccountFound = "noAccountFound"
    const val invalidEmailFormat = "invalidEmailFormat"
    const val authFailed = "authFailed"
    const val firstNameTooShort = "firstNameTooShort"
    const val invalidRegisterNumber = "invalidRegisterNumber"
    const val passwordTooShort = "passwordTooShort"
    const val signupFailedNoUser = "signupFailedNoUser"
    const val signupFailed = "signupFailed"
    const val failedToUnlink = "failedToUnlink"
    const val showPassword = "showPassword"
    const val hidePassword = "hidePassword"
    const val home = "home"
    const val calendar = "calendar"
    const val notes = "notes"
    const val notesDriveTab = "notesDriveTab"
    const val collegeSiteTab = "collegeSiteTab"
    const val notAvailable = "notAvailable"
    const val readMore = "readMore"
    const val today = "today"
    const val done = "done"

    // ── Prebuilt Notifications & UI Texts ──
    const val linkedin = "linkedin"
    const val github = "github"
    const val labForBatch = "labForBatch"
    const val authorAttribution = "authorAttribution"
    const val batchLabelFormat = "batchLabelFormat"
    const val registerRangeFormat = "registerRangeFormat"
    const val studentsCountFormat = "studentsCountFormat"
    const val newExamSchedule = "newExamSchedule"
    const val newExam = "newExam"
    const val examDatesRange = "examDatesRange"
    const val newHolidayAdded = "newHolidayAdded"
    const val newEvent = "newEvent"
    const val eventOnDate = "eventOnDate"
    const val newNotice = "newNotice"
    const val dailyUpdateFormat = "dailyUpdateFormat"
    const val newClassEvent = "newClassEvent"
    const val clipboardPdfLinkLabel = "clipboardPdfLinkLabel"
    const val rmkTitle = "rmkTitle"
    const val groupOfInstitutions = "groupOfInstitutions"
}
