import { StyleSheet } from 'react-native';

export const createAdminRoleManagerStyles = (colors) => StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: { padding: 16, flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border },
    backBtn: { padding: 8, marginRight: 8 },
    title: { fontSize: 20, fontWeight: '800', color: colors.textPrimary },
    subtitle: { fontSize: 13, color: colors.textSecondary },
    headerTitle: { fontSize: 20, fontWeight: '800', color: colors.textPrimary },
    searchBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.inputBackground, margin: 16, marginBottom: 8, paddingHorizontal: 12, borderRadius: 10, height: 46, borderWidth: 1, borderColor: colors.inputBorder },
    searchInput: { flex: 1, marginLeft: 8, fontSize: 16, color: colors.textPrimary },
    list: { padding: 16 },
    userCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, padding: 16, borderRadius: 16, marginBottom: 12, shadowOpacity: 0.05, elevation: 1 },
    avatar: { width: 50, height: 50, borderRadius: 25, backgroundColor: colors.subtleBackground, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
    userInfo: { flex: 1 },
    userName: { fontSize: 16, fontWeight: '700', color: colors.textPrimary },
    userRole: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
    roleBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8, backgroundColor: 'rgba(99, 102, 241, 0.1)' },
    roleBadgeText: { color: colors.accent, fontWeight: '700', fontSize: 12 },
    // Modal
    modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
    modalContent: { backgroundColor: colors.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, paddingBottom: 40 },
    modalTitle: { fontSize: 20, fontWeight: '800', color: colors.textPrimary, marginBottom: 4 },
    modalSubtitle: { fontSize: 14, color: colors.textSecondary, marginBottom: 24 },
    roleGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    roleOption: { width: '48%', backgroundColor: colors.subtleBackground, borderWidth: 2, borderColor: 'transparent', borderRadius: 16, padding: 16, alignItems: 'center' },
    roleOptionActive: { backgroundColor: colors.surface, borderColor: colors.accent },
    roleIcon: { width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
    roleLabel: { fontSize: 14, fontWeight: '600', color: colors.textPrimary },
    // Folders
    gridContent: { padding: 8, paddingBottom: 40 },
    folderGridItem: { flex: 1, aspectRatio: 1, margin: 8, backgroundColor: colors.surface, borderRadius: 16, justifyContent: 'center', alignItems: 'center', shadowOpacity: 0.05, elevation: 1 },
    folderIconLarge: { width: 60, height: 60, borderRadius: 30, backgroundColor: colors.subtleBackground, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
    folderLabel: { fontSize: 13, fontWeight: '600', color: colors.textPrimary, textAlign: 'center' },
    emptyText: { textAlign: 'center', marginTop: 40, color: colors.textSecondary },
    // Lock
    lockBadge: { position: 'absolute', bottom: 0, right: 0, backgroundColor: colors.textPrimary, borderRadius: 10, width: 16, height: 16, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: colors.surface, zIndex: 5 },
    systemAdminCard: { backgroundColor: colors.subtleBackground, borderWidth: 1, borderColor: colors.border },
    avatarImage: { width: 48, height: 48, resizeMode: 'cover', borderRadius: 24 },
    avatarText: { fontSize: 20, fontWeight: 'bold', color: colors.accent },
    userEmail: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
    badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
    badgeText: { fontSize: 10, fontWeight: '700' },

    // Helpers
    flex1: { flex: 1 },
    userRowHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    systemBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, backgroundColor: colors.accent },
    systemBadgeText: { fontSize: 10, fontWeight: '700', color: colors.buttonText },
    checkIcon: { position: 'absolute', top: 8, right: 8 },
    loader: { marginTop: 40 },
});
