import { StyleSheet } from 'react-native';

export const createAdminEventManagerStyles = (colors) => StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
        padding: 16,
        paddingTop: 8,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    backBtn: { marginRight: 16 },
    title: { fontSize: 18, fontWeight: 'bold', color: colors.textPrimary },
    subtitle: { fontSize: 12, color: colors.textSecondary },

    gridContent: { padding: 8, paddingBottom: 40 },
    list: { padding: 16, paddingBottom: 80 },
    emptyText: { textAlign: 'center', marginTop: 40, color: colors.textSecondary },

    // FOLDER GRID
    folderGridItem: {
        flex: 1,
        aspectRatio: 1,
        margin: 8,
        backgroundColor: colors.surface,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 8,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        elevation: 1,
    },
    folderIconLarge: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: colors.subtleBackground,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    folderLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.textPrimary,
        textAlign: 'center',
    },
    folderSubLabel: {
        fontSize: 10,
        color: colors.textSecondary,
        marginTop: 2,
    },

    // EVENT CARD
    card: {
        flexDirection: 'row',
        backgroundColor: colors.surface,
        borderRadius: 12,
        marginBottom: 12,
        overflow: 'hidden',
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        elevation: 1,
    },
    cardLeft: {
        width: 60,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.subtleBackground,
    },
    dateDay: { fontSize: 18, fontWeight: 'bold' },
    dateMonth: { fontSize: 11, fontWeight: '700', textTransform: 'uppercase' },
    cardBody: { flex: 1, padding: 12, justifyContent: 'center' },
    cardTitle: { fontSize: 15, fontWeight: '600', color: colors.textPrimary },
    cardSubtitle: { fontSize: 12, color: colors.textSecondary },
    cardDesc: { fontSize: 12, color: colors.textSecondary, fontStyle: 'italic', marginTop: 4 },
    typeBadge: {
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
    },
    iconBtn: { padding: 12, justifyContent: 'center' },

    // FAB
    fab: {
        position: 'absolute',
        bottom: 24,
        right: 24,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: colors.accent,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        elevation: 6,
    },

    // MODAL
    modalContainer: { flex: 1, backgroundColor: colors.surface },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    modalTitle: { fontSize: 18, fontWeight: 'bold', color: colors.textPrimary },
    form: { padding: 20 },
    label: { fontSize: 14, fontWeight: '600', color: colors.textSecondary, marginTop: 12, marginBottom: 8 },
    labelSmall: { fontSize: 12, fontWeight: '600', color: colors.textSecondary, marginBottom: 4 },
    input: {
        backgroundColor: colors.inputBackground,
        borderRadius: 8,
        padding: 12,
        borderWidth: 1,
        borderColor: colors.inputBorder,
        fontSize: 16,
        color: colors.textPrimary,
    },
    inputSmall: {
        backgroundColor: colors.inputBackground,
        borderRadius: 8,
        padding: 8,
        borderWidth: 1,
        borderColor: colors.inputBorder,
        fontSize: 14,
        color: colors.textPrimary,
    },
    dateBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.inputBackground,
        borderRadius: 8,
        padding: 12,
        gap: 8,
        borderWidth: 1,
        borderColor: colors.inputBorder,
    },
    dateBtnText: { fontSize: 16, fontWeight: '600', color: colors.textPrimary },

    typeRow: { flexDirection: 'row', gap: 8 },
    typeChip: {
        flex: 1,
        padding: 10,
        borderRadius: 8,
        backgroundColor: colors.inputBackground,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.inputBorder,
    },
    activeTypeChip: {
        backgroundColor: colors.accent,
        borderColor: colors.accent,
    },
    typeChipText: { fontWeight: '600', color: colors.textSecondary },

    halfDayBox: {
        backgroundColor: colors.subtleBackground,
        borderWidth: 1,
        borderColor: colors.warning,
        padding: 12,
        borderRadius: 8,
        marginTop: 12,
    },
    infoText: { fontSize: 12, color: colors.warning, marginTop: 8 },

    saveBtn: {
        backgroundColor: colors.accent,
        padding: 16,
        borderRadius: 12,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 32,
    },
    saveBtnText: { color: colors.buttonText, fontWeight: 'bold', fontSize: 16 },

    // TIME PICKER STYLES
    timeInputBtn: { backgroundColor: colors.inputBackground, borderRadius: 8, borderWidth: 1, borderColor: colors.inputBorder, padding: 8, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6 },
    timeInputText: { fontSize: 14, fontWeight: 'bold', color: colors.textPrimary },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: 20 },
    pickerContent: { backgroundColor: colors.surface, borderRadius: 16, padding: 16 },
    timeDisplayBox: { padding: 16, backgroundColor: colors.subtleBackground, borderRadius: 12, minWidth: 60, alignItems: 'center' },
    timeDisplayText: { fontSize: 24, fontWeight: 'bold', color: colors.textPrimary },
    timeOption: { paddingVertical: 10, alignItems: 'center', borderRadius: 8, marginVertical: 2 },
    activeTimeOption: { backgroundColor: colors.accent },
    activeTimeOptionText: { color: colors.buttonText, fontWeight: 'bold' },
    timeOptionText: { fontSize: 16, color: colors.textPrimary },
    colHeader: { textAlign: 'center', marginBottom: 8, color: colors.textSecondary, fontWeight: '600' },
    saveMainBtn: { backgroundColor: colors.accent, padding: 14, borderRadius: 12, alignItems: 'center', marginTop: 12 },
    saveMainBtnText: { color: colors.buttonText, fontWeight: 'bold', fontSize: 16 },

    // HELPERS
    flex1: { flex: 1 },
    marginTop40: { marginTop: 40 },
    rowGap6: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    textSmallBold: { fontSize: 10, fontWeight: 'bold' },
    paddingRight8: { justifyContent: 'center', paddingRight: 8 },
    textCancel: { fontSize: 16 },
    rowGap12: { flexDirection: 'row', gap: 12 },
    marginRight8: { marginRight: 8 },
    height40: { height: 40 },

    // TIME PICKER SPECIFIC
    pickerTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 16, textAlign: 'center', color: colors.textPrimary },
    pickerRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginBottom: 24 },
    pickerColon: { fontSize: 24, fontWeight: 'bold', marginHorizontal: 8, color: colors.textPrimary },
    pickerColumns: { flexDirection: 'row', height: 200, marginBottom: 16 },
    flex08: { flex: 0.8 },
    columnContent: { justifyContent: 'center', gap: 8, flex: 1 },
    marginLeft8MinWidth50: { marginLeft: 8, minWidth: 50 },
    fontSize18: { fontSize: 18 },
    inputTextArea: { height: 80, textAlignVertical: 'top' }
});
